# Site settings
author: Harley M Hanna
title: Metatron Analysis
header-img: img/home-bg.png
email: harleyhannawrit@gmail.com
copyright_name: Harley M Hanna
description: > # this means to ignore newlines until "baseurl:"
  There's going to be things here.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  HarleyHanna

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
